### ISSUE TITLE
Extract values of form fields without using the handleSubmit callback

### ISSUE THREAD

**Issue by JoseChavez98** [area2k/useForm#2]
Is there a way (without using the document property) of extracting the values of the form fields without using the handleSubmit ?.

The traditional way of handling forms is that you set state values for each of the fields, so you can manage them however you like. If, at some point, I want to use one of these values before pressing the submission button, how can I get these values?

**Comment by arempe93** [comment]
use `useField` to view the state of 1 field, or `useFormContext` to view the state of all fields
